import Head from 'next/head'
import Image from 'next/image'
import styled from '@emotion/styled'

import styles from '../styles/Home.module.css'

const Container = styled.div``;
const Main = styled.main``;
const BlogTitle = styled.h1`color: red`;

export default function Home() {
  const title: string = 'Nextjs blog'
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main className={styles.main}>
        <BlogTitle className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </BlogTitle>
      </Main>
    </div >
  )
}
